### PR TITLE
Update README.md - Added my contact details

### PR DESCRIPTION
**Pull request by supermacro**
I am interested in becoming a mentor for nodeschool

p.s. I've joined the slack channel as `giorgio`

### CODE REVIEW

**Comment by Rchristiani** [comment]
New event is on Sept 23rd! Please come out and hang out with us so we can meet you!

It will be a lot of fun!

**Comment by darcyclarke** [comment]
Hey @gDelgado14! I know you've come out a few times & you are enthusiastic :+1:; I also know this PR has been open for awhile (apologies). If you can come out to our next event (not schedule yet) we can chat about having you come mentor on a regular basis in person & add you to the list. For now, I'm going to close the PR but can reopen when I see you next.

**Comment by supermacro** [comment]
Hey @darcyclarke @Rchristiani ... my apologies for the late response. I was unavailable this past weekend. I hope to make it out for September though!

**Comment by ghost** [comment]
You are sending to the wrong giorgio

**Comment by darcyclarke** [comment]
@giorgio :( sorry

**Comment by ghost** [comment]
No problem.
I just let you know because the correct giorgio is presumably not getting
your messages.
Regards
George Richardson

Director Paua Software
Email: george@pauasoftware.co.nz
<http://pauasoftware.co.nz/>

**Pull request closed without merging**
