### PR TITLE
Fix up home page: event information, revert styling, ticket registration & more

### PR DESCRIPTION
**Pull request by darcyclarke**
screen

:+1: ? 

/cc @jeffjewiss @rickycodes @richgilbank @brenna @andrewdamelio @ahmadnassri @vladikoff @Rchristiani

### CODE REVIEW

**Comment by ahmadnassri** [comment]
:+1:

**Comment by Rchristiani** [comment]
This looks great! But I have one question...why no particles hahaha.(joking)

:+1:

**Comment by jeffjewiss** [comment]
:clap:

**Comment by vladikoff** [comment]
Awesome work Darcyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

**Comment by ahmadnassri** [comment]
lets start a "bring back the particles!" petition ...

**Comment by brenna** [comment]
lookin' good!

**Comment by andrewdamelio** [comment]
:+1: :+1: :+1:

**Pull request merged**
